// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKowFpPDUTTgHrW0mIlUvFPKYbxtf0d3k',
    appId: '1:655822390436:web:5f42d13bf8f75c88bd5231',
    messagingSenderId: '655822390436',
    projectId: 'journeys-e31cb',
    authDomain: 'journeys-e31cb.firebaseapp.com',
    storageBucket: 'journeys-e31cb.firebasestorage.app',
    measurementId: 'G-N7CLE0K9K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxo6IHs-Ix6jgkGSJfY6ZUcUZ8ybVPrb8',
    appId: '1:655822390436:android:2876dbda1deead8cbd5231',
    messagingSenderId: '655822390436',
    projectId: 'journeys-e31cb',
    storageBucket: 'journeys-e31cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCetYASa5oke0s-jKU8pdPu25G1Xmghic0',
    appId: '1:655822390436:ios:a1895a65251121f9bd5231',
    messagingSenderId: '655822390436',
    projectId: 'journeys-e31cb',
    storageBucket: 'journeys-e31cb.firebasestorage.app',
    iosBundleId: 'com.example.journeys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCetYASa5oke0s-jKU8pdPu25G1Xmghic0',
    appId: '1:655822390436:ios:a1895a65251121f9bd5231',
    messagingSenderId: '655822390436',
    projectId: 'journeys-e31cb',
    storageBucket: 'journeys-e31cb.firebasestorage.app',
    iosBundleId: 'com.example.journeys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKowFpPDUTTgHrW0mIlUvFPKYbxtf0d3k',
    appId: '1:655822390436:web:6309add8b2d42138bd5231',
    messagingSenderId: '655822390436',
    projectId: 'journeys-e31cb',
    authDomain: 'journeys-e31cb.firebaseapp.com',
    storageBucket: 'journeys-e31cb.firebasestorage.app',
    measurementId: 'G-MP8X9R9XQ8',
  );
}
